-- Script pour supprimer définitivement toutes les tables du restaurant
DROP TABLE IF EXISTS Unite CASCADE;
DROP TABLE IF EXISTS MaintenanceMaterielles CASCADE;
DROP TABLE IF EXISTS FacturesCommandes CASCADE;
DROP TABLE IF EXISTS DetailsCommandes CASCADE;
DROP TABLE IF EXISTS Commandes CASCADE;
DROP TABLE IF EXISTS ZonesLivraison CASCADE;
DROP TABLE IF EXISTS Clients CASCADE;
DROP TABLE IF EXISTS TypeClient CASCADE;

DROP TABLE IF EXISTS MouvementCaisse CASCADE;
DROP TABLE IF EXISTS TypeMouvementCaisse CASCADE;

DROP TABLE IF EXISTS BonusGlobaleSalairePersonnels CASCADE;
DROP TABLE IF EXISTS AbsencePersonnels CASCADE;
DROP TABLE IF EXISTS RaisonAbsence CASCADE;
DROP TABLE IF EXISTS HistoriqueSalaire CASCADE;
DROP TABLE IF EXISTS FichePaie CASCADE;
DROP TABLE IF EXISTS Personnels CASCADE;
DROP TABLE IF EXISTS RolePersonnels CASCADE;

DROP TABLE IF EXISTS RecettePlats CASCADE;
DROP TABLE IF EXISTS Plats CASCADE;
DROP TABLE IF EXISTS CategoriePlats CASCADE;

DROP TABLE IF EXISTS EtatStockIngredient CASCADE;
DROP TABLE IF EXISTS InventaireIngredient CASCADE;
DROP TABLE IF EXISTS TypeMvtIngredient CASCADE;
DROP TABLE IF EXISTS HistoriqueIngredients CASCADE;
DROP TABLE IF EXISTS Ingredients CASCADE;
DROP TABLE IF EXISTS StatutIngredient CASCADE;
DROP TABLE IF EXISTS CategorieIngredients CASCADE;

DROP TABLE IF EXISTS Fournisseurs CASCADE;
DROP TABLE IF EXISTS TypeFournisseurs CASCADE;

DROP TABLE IF EXISTS EtatStockMaterielles CASCADE;
DROP TABLE IF EXISTS InventairesMaterielles CASCADE;
DROP TABLE IF EXISTS TypeMvtMaterielles CASCADE;
DROP TABLE IF EXISTS HistoriqueMaterielles CASCADE;
DROP TABLE IF EXISTS Materielles CASCADE;
DROP TABLE IF EXISTS StatutMaterielles CASCADE;
DROP TABLE IF EXISTS CategorieMaterielles CASCADE;
DROP TABLE IF EXISTS MouvementCaisse CASCADE;
