sudo systemctl start postgresql
sudo systemctl enable postgresql
sudo -i -u postgres
psql
ALTER USER dev1 WITH dev;
CREATE DATABASE restaurant;
GRANT ALL PRIVILEGES ON DATABASE restaurant TO dev1;
GRANT USAGE ON SCHEMA public TO dev1;
GRANT CREATE ON SCHEMA public TO dev1;
GRANT USAGE ON SCHEMA public TO dev1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to dev1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to dev1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dev1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dev1;