-- Script pour vider les tables et réinitialiser les ID à 0 / 1
TRUNCATE TABLE 
    FacturesCommandes,
    DetailsCommandes,
    Commandes,
    ZonesLivraison,
    Clients,
    TypeClient,
    MouvementCaisse,
    TypeMouvementCaisse,
    BonusGlobaleSalairePersonnels,
    AbsencePersonnels,
    RaisonAbsence,
    HistoriqueSalaire,
    FichePaie,
    Personnels,
    RolePersonnels,
    RecettePlats,
    Plats,
    CategoriePlats,
    EtatStockIngredient,
    InventaireIngredient,
    TypeMvtIngredient,
    HistoriqueIngredients,
    Ingredients,
    StatutIngredient,
    CategorieIngredients,
    Fournisseurs,
    TypeFournisseurs,
    EtatStockMaterielles,
    InventairesMaterielles,
    TypeMvtMaterielles,
    HistoriqueMaterielles,
    Materielles,
    StatutMaterielles,
    CategorieMaterielles
RESTART IDENTITY CASCADE;
