-- Active: 1785442317642@@127.0.0.1@5432@restaurant@public
-- Script corrigé pour vider les tables et réinitialiser les identifiants
TRUNCATE TABLE 
    "facturescommandes",
    "detailscommandes",
    "commandes",
    "zoneslivraison",
    "clients",
    "typeclient",
    "mouvementcaisse",
    "typemouvementcaisse",
    "bonusglobalesalairepersonnels",
    "absencepersonnels",
    "raisonabsence",
    "historiquesalaire",
    "fichepaie",
    "personnels",
    "rolepersonnels",
    "recetteplats",
    "plats",
    "categorieplats",
    "etatstockingredient",
    "inventaireingredient",
    "typemvtingredient",
    "historiqueingredients",
    "ingredients",
    "statutingredient",
    "categorieingredients",
    "fournisseurs",
    "typefournisseurs",
    "etatstockmaterielles",
    "inventairesmaterielles",
    "typemvtmaterielles",
    "historiquematerielles",
    "materielles",
    "statutmaterielles",
    "categoriematerielles",
    "maintenancematerielles"
RESTART IDENTITY CASCADE;
