version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: restaurant
    restart: always
    environment:
      POSTGRES_USER: dev1
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: restaurant # Aligné avec application.properties
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # On pointe sur le nom du service "db" et la base "restaurant"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant
      SPRING_DATASOURCE_USERNAME: dev1
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: